name: OpenAlarm
options:
  minimumXcodeGenVersion: 2.44.1
  createIntermediateGroups: true
settings:
  base:
    DEVELOPMENT_LANGUAGE: en

targets:
  OpenAlarm:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: OpenAlarm
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gretzke.openalarm
        PRODUCT_NAME: OpenAlarm
        DEVELOPMENT_TEAM: 7P7CKKPH5L
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: 5.0
        CURRENT_PROJECT_VERSION: 28
        MARKETING_VERSION: 0.1.0
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: OpenAlarm/Info.plist
        LOCALIZATIONS: "en de"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
